### ISSUE TITLE
judges and placements

### ISSUE THREAD

**Issue by gregbo** [GassiusODude/relative-placement#1]
- The version of RP that is documented at the WSDC site allows an even number (excluding the chief judge) of judges to be used, although it recommends an odd number.

- There are times when the judges are instructed to give unique placements only up to a certain number of contestants, after which the remaining contestants get the same placement.  For example, see the [2016 US Open Classic Prelims](https://docs.google.com/spreadsheets/d/e/2PACX-1vQurYH7W7C9h5C4R4BC2DHCPilNeXU2DCcMIZJxoLuovvKLJ1pl_kyEeR9mept-3hmVcp3IVucq0YCO/pubhtml#).  (Click on the 'Classic Prelim' tab near the top of the page.)

**Comment by GassiusODude** [comment]
@gregbo Thanks for taking a look at this project and providing your feedback.  I do recall limiting the initial use case  to the common case that I was familiar with (odd number of judges)  I will have to review what is currently implemented and gain an understanding of the use cases that you referenced.
